# Generated by Django 4.2.2 on 2023-07-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_alter_directorgeneral_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='sin especificar', verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='sin especificar', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='sin especificar', verbose_name='Pais'),
        ),
    ]
